version: '3.8'

networks:
  edunet:
    driver: bridge

services:
  db:
    image: pgvector/pgvector:pg17
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    container_name: postgres-db
    env_file: ".env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./migration/versions:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - edunet
  asr:
    build:
      context: .
      dockerfile: asr/Dockerfile
    container_name: asr_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
     - edunet
  llm:
    build:
      context: .
      dockerfile: llm/Dockerfile
    container_name: llm_service
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
       db:
        condition: service_healthy
    networks:
     - edunet
  docling-serve:
    image: ghcr.io/docling-project/docling-serve:latest
    container_name: docling-serve
    env_file:
      - .env
    ports:
      - "8080:5001"
    environment:
      DOCLING_SERVE_SCRATCH_PATH: /tmp/docling
    volumes:
      - ./scratch:/tmp/docling
    restart: unless-stopped
    networks:
     - edunet
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    restart: unless-stopped
    networks:
     - edunet


volumes:
  postgres_data: